var c = [
    {
        "libelle": "tache 0",
        "deb": 1491870600000,
        "fin": 1491890400000,
        "debLit": "02:30",
        "finLit": "08:00",
        "timeSlotRequired": 11,
        "slotDeb": 5,
        "slotFin": 16
    },
    {
        "libelle": "tache 1",
        "deb": 1491933600000,
        "fin": 1491939000000,
        "debLit": "20:00",
        "finLit": "21:30",
        "timeSlotRequired": 3,
        "slotDeb": 40,
        "slotFin": 43
    },
    {
        "libelle": "tache 2",
        "deb": 1491876000000,
        "fin": 1491899400000,
        "debLit": "04:00",
        "finLit": "10:30",
        "timeSlotRequired": 13,
        "slotDeb": 8,
        "slotFin": 21
    },
    {
        "libelle": "tache 3",
        "deb": 1491908400000,
        "fin": 1491915600000,
        "debLit": "13:00",
        "finLit": "15:00",
        "timeSlotRequired": 4,
        "slotDeb": 26,
        "slotFin": 30
    },
    {
        "libelle": "tache 4",
        "deb": 1491863400000,
        "fin": 1491890400000,
        "debLit": "00:30",
        "finLit": "08:00",
        "timeSlotRequired": 15,
        "slotDeb": 1,
        "slotFin": 16
    },
    {
        "libelle": "tache 5",
        "deb": 1491897600000,
        "fin": 1491921000000,
        "debLit": "10:00",
        "finLit": "16:30",
        "timeSlotRequired": 13,
        "slotDeb": 20,
        "slotFin": 33
    },
    {
        "libelle": "tache 6",
        "deb": 1491879600000,
        "fin": 1491894000000,
        "debLit": "05:00",
        "finLit": "09:00",
        "timeSlotRequired": 8,
        "slotDeb": 10,
        "slotFin": 18
    },
    {
        "libelle": "tache 7",
        "deb": 1491924600000,
        "fin": 1491937200000,
        "debLit": "17:30",
        "finLit": "21:00",
        "timeSlotRequired": 7,
        "slotDeb": 35,
        "slotFin": 42
    },
    {
        "libelle": "tache 8",
        "deb": 1491894000000,
        "fin": 1491906600000,
        "debLit": "09:00",
        "finLit": "12:30",
        "timeSlotRequired": 7,
        "slotDeb": 18,
        "slotFin": 25
    },
    {
        "libelle": "tache 9",
        "deb": 1491890400000,
        "fin": 1491903000000,
        "debLit": "08:00",
        "finLit": "11:30",
        "timeSlotRequired": 7,
        "slotDeb": 16,
        "slotFin": 23
    },
    {
        "libelle": "tache 10",
        "deb": 1491944400000,
        "fin": 1491948000000,
        "debLit": "23:00",
        "finLit": "00:00",
        "timeSlotRequired": 2,
        "slotDeb": 46,
        "slotFin": 48
    },
    {
        "libelle": "tache 11",
        "deb": 1491903000000,
        "fin": 1491930000000,
        "debLit": "11:30",
        "finLit": "19:00",
        "timeSlotRequired": 15,
        "slotDeb": 23,
        "slotFin": 38
    },
    {
        "libelle": "tache 12",
        "deb": 1491946200000,
        "fin": 1491948000000,
        "debLit": "23:30",
        "finLit": "00:00",
        "timeSlotRequired": 1,
        "slotDeb": 47,
        "slotFin": 48
    },
    {
        "libelle": "tache 13",
        "deb": 1491885000000,
        "fin": 1491894000000,
        "debLit": "06:30",
        "finLit": "09:00",
        "timeSlotRequired": 5,
        "slotDeb": 13,
        "slotFin": 18
    },
    {
        "libelle": "tache 14",
        "deb": 1491886800000,
        "fin": 1491913800000,
        "debLit": "07:00",
        "finLit": "14:30",
        "timeSlotRequired": 15,
        "slotDeb": 14,
        "slotFin": 29
    },
    {
        "libelle": "tache 15",
        "deb": 1491946200000,
        "fin": 1491948000000,
        "debLit": "23:30",
        "finLit": "00:00",
        "timeSlotRequired": 1,
        "slotDeb": 47,
        "slotFin": 48
    },
    {
        "libelle": "tache 16",
        "deb": 1491876000000,
        "fin": 1491903000000,
        "debLit": "04:00",
        "finLit": "11:30",
        "timeSlotRequired": 15,
        "slotDeb": 8,
        "slotFin": 23
    },
    {
        "libelle": "tache 17",
        "deb": 1491935400000,
        "fin": 1491942600000,
        "debLit": "20:30",
        "finLit": "22:30",
        "timeSlotRequired": 4,
        "slotDeb": 41,
        "slotFin": 45
    },
    {
        "libelle": "tache 18",
        "deb": 1491910200000,
        "fin": 1491928200000,
        "debLit": "13:30",
        "finLit": "18:30",
        "timeSlotRequired": 10,
        "slotDeb": 27,
        "slotFin": 37
    },
    {
        "libelle": "tache 19",
        "deb": 1491922800000,
        "fin": 1491940800000,
        "debLit": "17:00",
        "finLit": "22:00",
        "timeSlotRequired": 10,
        "slotDeb": 34,
        "slotFin": 44
    },
    {
        "libelle": "tache 20",
        "deb": 1491894000000,
        "fin": 1491901200000,
        "debLit": "09:00",
        "finLit": "11:00",
        "timeSlotRequired": 4,
        "slotDeb": 18,
        "slotFin": 22
    },
    {
        "libelle": "tache 21",
        "deb": 1491921000000,
        "fin": 1491946200000,
        "debLit": "16:30",
        "finLit": "23:30",
        "timeSlotRequired": 14,
        "slotDeb": 33,
        "slotFin": 47
    },
    {
        "libelle": "tache 22",
        "deb": 1491879600000,
        "fin": 1491897600000,
        "debLit": "05:00",
        "finLit": "10:00",
        "timeSlotRequired": 10,
        "slotDeb": 10,
        "slotFin": 20
    },
    {
        "libelle": "tache 23",
        "deb": 1491877800000,
        "fin": 1491903000000,
        "debLit": "04:30",
        "finLit": "11:30",
        "timeSlotRequired": 14,
        "slotDeb": 9,
        "slotFin": 23
    },
    {
        "libelle": "tache 24",
        "deb": 1491874200000,
        "fin": 1491901200000,
        "debLit": "03:30",
        "finLit": "11:00",
        "timeSlotRequired": 15,
        "slotDeb": 7,
        "slotFin": 22
    },
    {
        "libelle": "tache 25",
        "deb": 1491895800000,
        "fin": 1491906600000,
        "debLit": "09:30",
        "finLit": "12:30",
        "timeSlotRequired": 6,
        "slotDeb": 19,
        "slotFin": 25
    },
    {
        "libelle": "tache 26",
        "deb": 1491906600000,
        "fin": 1491933600000,
        "debLit": "12:30",
        "finLit": "20:00",
        "timeSlotRequired": 15,
        "slotDeb": 25,
        "slotFin": 40
    },
    {
        "libelle": "tache 27",
        "deb": 1491933600000,
        "fin": 1491940800000,
        "debLit": "20:00",
        "finLit": "22:00",
        "timeSlotRequired": 4,
        "slotDeb": 40,
        "slotFin": 44
    },
    {
        "libelle": "tache 28",
        "deb": 1491939000000,
        "fin": 1491948000000,
        "debLit": "21:30",
        "finLit": "00:00",
        "timeSlotRequired": 5,
        "slotDeb": 43,
        "slotFin": 48
    },
    {
        "libelle": "tache 29",
        "deb": 1491908400000,
        "fin": 1491924600000,
        "debLit": "13:00",
        "finLit": "17:30",
        "timeSlotRequired": 9,
        "slotDeb": 26,
        "slotFin": 35
    },
    {
        "libelle": "tache 30",
        "deb": 1491877800000,
        "fin": 1491904800000,
        "debLit": "04:30",
        "finLit": "12:00",
        "timeSlotRequired": 15,
        "slotDeb": 9,
        "slotFin": 24
    },
    {
        "libelle": "tache 31",
        "deb": 1491921000000,
        "fin": 1491946200000,
        "debLit": "16:30",
        "finLit": "23:30",
        "timeSlotRequired": 14,
        "slotDeb": 33,
        "slotFin": 47
    },
    {
        "libelle": "tache 32",
        "deb": 1491881400000,
        "fin": 1491903000000,
        "debLit": "05:30",
        "finLit": "11:30",
        "timeSlotRequired": 12,
        "slotDeb": 11,
        "slotFin": 23
    },
    {
        "libelle": "tache 33",
        "deb": 1491904800000,
        "fin": 1491931800000,
        "debLit": "12:00",
        "finLit": "19:30",
        "timeSlotRequired": 15,
        "slotDeb": 24,
        "slotFin": 39
    },
    {
        "libelle": "tache 34",
        "deb": 1491894000000,
        "fin": 1491897600000,
        "debLit": "09:00",
        "finLit": "10:00",
        "timeSlotRequired": 2,
        "slotDeb": 18,
        "slotFin": 20
    },
    {
        "libelle": "tache 35",
        "deb": 1491868800000,
        "fin": 1491876000000,
        "debLit": "02:00",
        "finLit": "04:00",
        "timeSlotRequired": 4,
        "slotDeb": 4,
        "slotFin": 8
    },
    {
        "libelle": "tache 36",
        "deb": 1491890400000,
        "fin": 1491917400000,
        "debLit": "08:00",
        "finLit": "15:30",
        "timeSlotRequired": 15,
        "slotDeb": 16,
        "slotFin": 31
    },
    {
        "libelle": "tache 37",
        "deb": 1491876000000,
        "fin": 1491892200000,
        "debLit": "04:00",
        "finLit": "08:30",
        "timeSlotRequired": 9,
        "slotDeb": 8,
        "slotFin": 17
    },
    {
        "libelle": "tache 38",
        "deb": 1491904800000,
        "fin": 1491931800000,
        "debLit": "12:00",
        "finLit": "19:30",
        "timeSlotRequired": 15,
        "slotDeb": 24,
        "slotFin": 39
    },
    {
        "libelle": "tache 39",
        "deb": 1491913800000,
        "fin": 1491940800000,
        "debLit": "14:30",
        "finLit": "22:00",
        "timeSlotRequired": 15,
        "slotDeb": 29,
        "slotFin": 44
    }
];
var datasResult = {
    "solution": {
        "fitness": {
            "scoreOverlap": 40,
            "nuits": 133,
            "improductivity": 207,
            "nbVacs": 39,
            "value": 421.95,
            "detailsScore": {
                "v": 48,
                "imp": 79.35000000000001,
                "n": 294.59999999999997
            }
        },
        "vacationList": [
            {
                "debVac": 4,
                "finVac": 19,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 0": {
                        "libelle": "tache 0",
                        "deb": 1491870600000,
                        "fin": 1491890400000,
                        "debLit": "02:30",
                        "finLit": "08:00",
                        "timeSlotRequired": 11,
                        "slotDeb": 5,
                        "slotFin": 16
                    }
                }
            },
            {
                "debVac": 28,
                "finVac": 43,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 1": {
                        "libelle": "tache 1",
                        "deb": 1491933600000,
                        "fin": 1491939000000,
                        "debLit": "20:00",
                        "finLit": "21:30",
                        "timeSlotRequired": 3,
                        "slotDeb": 40,
                        "slotFin": 43
                    }
                }
            },
            {
                "debVac": 7,
                "finVac": 22,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 34": {
                        "libelle": "tache 34",
                        "deb": 1491894000000,
                        "fin": 1491897600000,
                        "debLit": "09:00",
                        "finLit": "10:00",
                        "timeSlotRequired": 2,
                        "slotDeb": 18,
                        "slotFin": 20
                    }
                }
            },
            {
                "debVac": 21,
                "finVac": 36,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 3": {
                        "libelle": "tache 3",
                        "deb": 1491908400000,
                        "fin": 1491915600000,
                        "debLit": "13:00",
                        "finLit": "15:00",
                        "timeSlotRequired": 4,
                        "slotDeb": 26,
                        "slotFin": 30
                    }
                }
            },
            {
                "debVac": 19,
                "finVac": 34,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 5": {
                        "libelle": "tache 5",
                        "deb": 1491897600000,
                        "fin": 1491921000000,
                        "debLit": "10:00",
                        "finLit": "16:30",
                        "timeSlotRequired": 13,
                        "slotDeb": 20,
                        "slotFin": 33
                    }
                }
            },
            {
                "debVac": 28,
                "finVac": 43,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 7": {
                        "libelle": "tache 7",
                        "deb": 1491924600000,
                        "fin": 1491937200000,
                        "debLit": "17:30",
                        "finLit": "21:00",
                        "timeSlotRequired": 7,
                        "slotDeb": 35,
                        "slotFin": 42
                    }
                }
            },
            {
                "debVac": 15,
                "finVac": 30,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 9": {
                        "libelle": "tache 9",
                        "deb": 1491890400000,
                        "fin": 1491903000000,
                        "debLit": "08:00",
                        "finLit": "11:30",
                        "timeSlotRequired": 7,
                        "slotDeb": 16,
                        "slotFin": 23
                    }
                }
            },
            {
                "debVac": 33,
                "finVac": 48,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    1
                ],
                "taches": {
                    "tache 12": {
                        "libelle": "tache 12",
                        "deb": 1491946200000,
                        "fin": 1491948000000,
                        "debLit": "23:30",
                        "finLit": "00:00",
                        "timeSlotRequired": 1,
                        "slotDeb": 47,
                        "slotFin": 48
                    },
                    "tache 19": {
                        "libelle": "tache 19",
                        "deb": 1491922800000,
                        "fin": 1491940800000,
                        "debLit": "17:00",
                        "finLit": "22:00",
                        "timeSlotRequired": 10,
                        "slotDeb": 34,
                        "slotFin": 44
                    }
                }
            },
            {
                "debVac": 23,
                "finVac": 38,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 11": {
                        "libelle": "tache 11",
                        "deb": 1491903000000,
                        "fin": 1491930000000,
                        "debLit": "11:30",
                        "finLit": "19:00",
                        "timeSlotRequired": 15,
                        "slotDeb": 23,
                        "slotFin": 38
                    }
                }
            },
            {
                "debVac": 3,
                "finVac": 18,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 13": {
                        "libelle": "tache 13",
                        "deb": 1491885000000,
                        "fin": 1491894000000,
                        "debLit": "06:30",
                        "finLit": "09:00",
                        "timeSlotRequired": 5,
                        "slotDeb": 13,
                        "slotFin": 18
                    }
                }
            },
            {
                "debVac": 33,
                "finVac": 48,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1
                ],
                "taches": {
                    "tache 15": {
                        "libelle": "tache 15",
                        "deb": 1491946200000,
                        "fin": 1491948000000,
                        "debLit": "23:30",
                        "finLit": "00:00",
                        "timeSlotRequired": 1,
                        "slotDeb": 47,
                        "slotFin": 48
                    }
                }
            },
            {
                "debVac": 8,
                "finVac": 23,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 16": {
                        "libelle": "tache 16",
                        "deb": 1491876000000,
                        "fin": 1491903000000,
                        "debLit": "04:00",
                        "finLit": "11:30",
                        "timeSlotRequired": 15,
                        "slotDeb": 8,
                        "slotFin": 23
                    }
                }
            },
            {
                "debVac": 7,
                "finVac": 22,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 20": {
                        "libelle": "tache 20",
                        "deb": 1491894000000,
                        "fin": 1491901200000,
                        "debLit": "09:00",
                        "finLit": "11:00",
                        "timeSlotRequired": 4,
                        "slotDeb": 18,
                        "slotFin": 22
                    }
                }
            },
            {
                "debVac": 32,
                "finVac": 47,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0
                ],
                "taches": {
                    "tache 21": {
                        "libelle": "tache 21",
                        "deb": 1491921000000,
                        "fin": 1491946200000,
                        "debLit": "16:30",
                        "finLit": "23:30",
                        "timeSlotRequired": 14,
                        "slotDeb": 33,
                        "slotFin": 47
                    }
                }
            },
            {
                "debVac": 7,
                "finVac": 22,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 24": {
                        "libelle": "tache 24",
                        "deb": 1491874200000,
                        "fin": 1491901200000,
                        "debLit": "03:30",
                        "finLit": "11:00",
                        "timeSlotRequired": 15,
                        "slotDeb": 7,
                        "slotFin": 22
                    }
                }
            },
            {
                "debVac": 25,
                "finVac": 40,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 26": {
                        "libelle": "tache 26",
                        "deb": 1491906600000,
                        "fin": 1491933600000,
                        "debLit": "12:30",
                        "finLit": "20:00",
                        "timeSlotRequired": 15,
                        "slotDeb": 25,
                        "slotFin": 40
                    }
                }
            },
            {
                "debVac": 30,
                "finVac": 45,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 27": {
                        "libelle": "tache 27",
                        "deb": 1491933600000,
                        "fin": 1491940800000,
                        "debLit": "20:00",
                        "finLit": "22:00",
                        "timeSlotRequired": 4,
                        "slotDeb": 40,
                        "slotFin": 44
                    }
                }
            },
            {
                "debVac": 33,
                "finVac": 48,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1
                ],
                "taches": {
                    "tache 28": {
                        "libelle": "tache 28",
                        "deb": 1491939000000,
                        "fin": 1491948000000,
                        "debLit": "21:30",
                        "finLit": "00:00",
                        "timeSlotRequired": 5,
                        "slotDeb": 43,
                        "slotFin": 48
                    }
                }
            },
            {
                "debVac": 9,
                "finVac": 24,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 30": {
                        "libelle": "tache 30",
                        "deb": 1491877800000,
                        "fin": 1491904800000,
                        "debLit": "04:30",
                        "finLit": "12:00",
                        "timeSlotRequired": 15,
                        "slotDeb": 9,
                        "slotFin": 24
                    }
                }
            },
            {
                "debVac": 24,
                "finVac": 39,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 33": {
                        "libelle": "tache 33",
                        "deb": 1491904800000,
                        "fin": 1491931800000,
                        "debLit": "12:00",
                        "finLit": "19:30",
                        "timeSlotRequired": 15,
                        "slotDeb": 24,
                        "slotFin": 39
                    }
                }
            },
            {
                "debVac": 16,
                "finVac": 31,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 36": {
                        "libelle": "tache 36",
                        "deb": 1491890400000,
                        "fin": 1491917400000,
                        "debLit": "08:00",
                        "finLit": "15:30",
                        "timeSlotRequired": 15,
                        "slotDeb": 16,
                        "slotFin": 31
                    }
                }
            },
            {
                "debVac": 5,
                "finVac": 20,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 37": {
                        "libelle": "tache 37",
                        "deb": 1491876000000,
                        "fin": 1491892200000,
                        "debLit": "04:00",
                        "finLit": "08:30",
                        "timeSlotRequired": 9,
                        "slotDeb": 8,
                        "slotFin": 17
                    }
                }
            },
            {
                "debVac": 29,
                "finVac": 44,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 39": {
                        "libelle": "tache 39",
                        "deb": 1491913800000,
                        "fin": 1491940800000,
                        "debLit": "14:30",
                        "finLit": "22:00",
                        "timeSlotRequired": 15,
                        "slotDeb": 29,
                        "slotFin": 44
                    }
                }
            },
            {
                "debVac": 30,
                "finVac": 45,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 17": {
                        "libelle": "tache 17",
                        "deb": 1491935400000,
                        "fin": 1491942600000,
                        "debLit": "20:30",
                        "finLit": "22:30",
                        "timeSlotRequired": 4,
                        "slotDeb": 41,
                        "slotFin": 45
                    }
                }
            },
            {
                "debVac": 3,
                "finVac": 18,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 35": {
                        "libelle": "tache 35",
                        "deb": 1491868800000,
                        "fin": 1491876000000,
                        "debLit": "02:00",
                        "finLit": "04:00",
                        "timeSlotRequired": 4,
                        "slotDeb": 4,
                        "slotFin": 8
                    }
                }
            },
            {
                "debVac": 7,
                "finVac": 22,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 22": {
                        "libelle": "tache 22",
                        "deb": 1491879600000,
                        "fin": 1491897600000,
                        "debLit": "05:00",
                        "finLit": "10:00",
                        "timeSlotRequired": 10,
                        "slotDeb": 10,
                        "slotFin": 20
                    }
                }
            },
            {
                "debVac": 26,
                "finVac": 41,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 18": {
                        "libelle": "tache 18",
                        "deb": 1491910200000,
                        "fin": 1491928200000,
                        "debLit": "13:30",
                        "finLit": "18:30",
                        "timeSlotRequired": 10,
                        "slotDeb": 27,
                        "slotFin": 37
                    }
                }
            },
            {
                "debVac": 33,
                "finVac": 48,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1
                ],
                "taches": {
                    "tache 10": {
                        "libelle": "tache 10",
                        "deb": 1491944400000,
                        "fin": 1491948000000,
                        "debLit": "23:00",
                        "finLit": "00:00",
                        "timeSlotRequired": 2,
                        "slotDeb": 46,
                        "slotFin": 48
                    }
                }
            },
            {
                "debVac": 19,
                "finVac": 34,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 25": {
                        "libelle": "tache 25",
                        "deb": 1491895800000,
                        "fin": 1491906600000,
                        "debLit": "09:30",
                        "finLit": "12:30",
                        "timeSlotRequired": 6,
                        "slotDeb": 19,
                        "slotFin": 25
                    }
                }
            },
            {
                "debVac": 9,
                "finVac": 24,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 23": {
                        "libelle": "tache 23",
                        "deb": 1491877800000,
                        "fin": 1491903000000,
                        "debLit": "04:30",
                        "finLit": "11:30",
                        "timeSlotRequired": 14,
                        "slotDeb": 9,
                        "slotFin": 23
                    }
                }
            },
            {
                "debVac": 7,
                "finVac": 22,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 2": {
                        "libelle": "tache 2",
                        "deb": 1491876000000,
                        "fin": 1491899400000,
                        "debLit": "04:00",
                        "finLit": "10:30",
                        "timeSlotRequired": 13,
                        "slotDeb": 8,
                        "slotFin": 21
                    }
                }
            },
            {
                "debVac": 9,
                "finVac": 24,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 32": {
                        "libelle": "tache 32",
                        "deb": 1491881400000,
                        "fin": 1491903000000,
                        "debLit": "05:30",
                        "finLit": "11:30",
                        "timeSlotRequired": 12,
                        "slotDeb": 11,
                        "slotFin": 23
                    }
                }
            },
            {
                "debVac": 24,
                "finVac": 39,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 38": {
                        "libelle": "tache 38",
                        "deb": 1491904800000,
                        "fin": 1491931800000,
                        "debLit": "12:00",
                        "finLit": "19:30",
                        "timeSlotRequired": 15,
                        "slotDeb": 24,
                        "slotFin": 39
                    }
                }
            },
            {
                "debVac": 32,
                "finVac": 47,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0
                ],
                "taches": {
                    "tache 31": {
                        "libelle": "tache 31",
                        "deb": 1491921000000,
                        "fin": 1491946200000,
                        "debLit": "16:30",
                        "finLit": "23:30",
                        "timeSlotRequired": 14,
                        "slotDeb": 33,
                        "slotFin": 47
                    }
                }
            },
            {
                "debVac": 22,
                "finVac": 37,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 29": {
                        "libelle": "tache 29",
                        "deb": 1491908400000,
                        "fin": 1491924600000,
                        "debLit": "13:00",
                        "finLit": "17:30",
                        "timeSlotRequired": 9,
                        "slotDeb": 26,
                        "slotFin": 35
                    }
                }
            },
            {
                "debVac": 18,
                "finVac": 33,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 8": {
                        "libelle": "tache 8",
                        "deb": 1491894000000,
                        "fin": 1491906600000,
                        "debLit": "09:00",
                        "finLit": "12:30",
                        "timeSlotRequired": 7,
                        "slotDeb": 18,
                        "slotFin": 25
                    }
                }
            },
            {
                "debVac": 14,
                "finVac": 29,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 14": {
                        "libelle": "tache 14",
                        "deb": 1491886800000,
                        "fin": 1491913800000,
                        "debLit": "07:00",
                        "finLit": "14:30",
                        "timeSlotRequired": 15,
                        "slotDeb": 14,
                        "slotFin": 29
                    }
                }
            },
            {
                "debVac": 5,
                "finVac": 20,
                "slots": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 6": {
                        "libelle": "tache 6",
                        "deb": 1491879600000,
                        "fin": 1491894000000,
                        "debLit": "05:00",
                        "finLit": "09:00",
                        "timeSlotRequired": 8,
                        "slotDeb": 10,
                        "slotFin": 18
                    }
                }
            },
            {
                "debVac": 1,
                "finVac": 16,
                "slots": [
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "taches": {
                    "tache 4": {
                        "libelle": "tache 4",
                        "deb": 1491863400000,
                        "fin": 1491890400000,
                        "debLit": "00:30",
                        "finLit": "08:00",
                        "timeSlotRequired": 15,
                        "slotDeb": 1,
                        "slotFin": 16
                    }
                }
            }
        ],
        "chargeMap": {
            "tache 0": 0,
            "tache 1": 1,
            "tache 2": 30,
            "tache 3": 3,
            "tache 4": 38,
            "tache 5": 4,
            "tache 6": 37,
            "tache 7": 5,
            "tache 8": 35,
            "tache 9": 6,
            "tache 10": 27,
            "tache 11": 8,
            "tache 12": 7,
            "tache 13": 9,
            "tache 14": 36,
            "tache 15": 10,
            "tache 16": 11,
            "tache 17": 23,
            "tache 18": 26,
            "tache 19": 7,
            "tache 20": 12,
            "tache 21": 13,
            "tache 22": 25,
            "tache 23": 29,
            "tache 24": 14,
            "tache 25": 28,
            "tache 26": 15,
            "tache 27": 16,
            "tache 28": 17,
            "tache 29": 34,
            "tache 30": 18,
            "tache 31": 33,
            "tache 32": 31,
            "tache 33": 19,
            "tache 34": 2,
            "tache 35": 24,
            "tache 36": 20,
            "tache 37": 21,
            "tache 38": 32,
            "tache 39": 22
        }
    },
    "index": 48,
    "score": 421.95
};